### ISSUE TITLE
Post date needs to be fixed

### ISSUE THREAD

**Issue by wanseob** [ethcon-kr/contributhon#48]
![image](https://user-images.githubusercontent.com/8542397/66052425-8a88e700-e56b-11e9-889c-fe66d4baa8e9.png)

@HackerEunji 

Please update the date of the post to when you published it.

**Comment by wanseob** [comment]
@HackerEunji Would you please check this file also?

**Comment by HackerEunji** [comment]
I edited and automatically pushed this content through [2019-09-29-eunji-translation.md] file. I'm afraid I did something wrong again. Anyway, how the date 2019-09-06  can be made though I didn't type any "2019-09-06" on file?

**Comment by wanseob** [comment]
You need to change the date in the file.

Click the edit button here
![image](https://user-images.githubusercontent.com/8542397/67063906-64865800-f1a3-11e9-8072-328a7e6d9708.png)

And change the date here :)
![image](https://user-images.githubusercontent.com/8542397/67063927-75cf6480-f1a3-11e9-9c9a-c5cf35b69a4b.png)

Or you can go to change it through this link https://github.com/ethcon-kr/contributhon/edit/master/_posts/2019-09-29-eunji-translation.md

**Comment by wanseob** [comment]
Closed by commit https://github.com/ethcon-kr/contributhon/commit/67dd6bf886643349438808a04e784632d6aec5b4.
